"""
Proxy setup — routes all requests traffic through a SOCKS5 proxy (e.g. Tor).

Call `apply_proxy()` once at startup, before any HTTP calls are made.
This patches the default requests session so that ALL libraries using
requests (including py_clob_client) automatically go through the proxy.

For Tor, call `ensure_tor()` to auto-generate a torrc that pins exit nodes
to Polymarket-friendly countries and (re)start Tor with it.
"""

import logging
import os
import shutil
import signal
import subprocess
from pathlib import Path
from typing import Optional

logger = logging.getLogger("polly.proxy")

_patched = False

# Polymarket-friendly countries that ALSO have Tor exit nodes.
# Must satisfy BOTH: (a) not on Polymarket blocklist, (b) actually has exit relays.
#
# Blocked by Polymarket (cannot use):
#   US, UK, FR, DE, NL, IT, BE, AU, BY, CU, IR, IQ, KP, RU, ...
# Close-only (cannot open new trades):
#   PL, SG, TH, TW
#
# Countries with near-zero Tor exits removed (MY, PH, KE, NG, AE, HK, CO, ID, etc.)
# to avoid StrictNodes causing bootstrap hangs.
DEFAULT_EXIT_COUNTRIES = [
    "{ch}",  # Switzerland   — many exit nodes
    "{se}",  # Sweden        — good availability
    "{ro}",  # Romania       — good availability
    "{cz}",  # Czech Republic — good availability
    "{at}",  # Austria       — moderate
    "{es}",  # Spain         — moderate
    "{dk}",  # Denmark       — some
    "{fi}",  # Finland       — some
    "{no}",  # Norway        — some
    "{pt}",  # Portugal      — some
    "{br}",  # Brazil        — some
    "{jp}",  # Japan         — few but present
    "{kr}",  # South Korea   — few but present
    "{in}",  # India         — few but present
]

TORRC_DIR = Path(__file__).resolve().parent.parent / ".tor"
TORRC_PATH = TORRC_DIR / "torrc"
TOR_DATA_DIR = TORRC_DIR / "data"
TOR_PID_FILE = TORRC_DIR / "tor.pid"
TOR_SOCKS_PORT = 9050


def _write_torrc(exit_countries: Optional[list[str]] = None) -> Path:
    """Generate a torrc file that pins exit nodes to friendly countries."""
    countries = exit_countries or DEFAULT_EXIT_COUNTRIES
    TORRC_DIR.mkdir(parents=True, exist_ok=True)
    TOR_DATA_DIR.mkdir(parents=True, exist_ok=True)

    torrc_content = f"""\
# Auto-generated by Poly Wants A Cracker
# Pins Tor exit nodes to Polymarket-friendly regions.

SocksPort {TOR_SOCKS_PORT}
DataDirectory {TOR_DATA_DIR}

# Only use exit nodes in these countries
ExitNodes {",".join(countries)}
StrictNodes 1
"""
    TORRC_PATH.write_text(torrc_content)
    logger.info(f"Wrote torrc with exit countries: {', '.join(countries)}")
    return TORRC_PATH


def _is_tor_running() -> bool:
    """Check if our managed Tor instance is running."""
    if not TOR_PID_FILE.exists():
        return False
    try:
        pid = int(TOR_PID_FILE.read_text().strip())
        os.kill(pid, 0)  # signal 0 = check if alive
        return True
    except (ValueError, ProcessLookupError, PermissionError):
        TOR_PID_FILE.unlink(missing_ok=True)
        return False


def _stop_tor() -> None:
    """Stop our managed Tor instance if running."""
    if not TOR_PID_FILE.exists():
        return
    try:
        pid = int(TOR_PID_FILE.read_text().strip())
        os.kill(pid, signal.SIGTERM)
        logger.info(f"Stopped Tor (pid {pid})")
    except (ValueError, ProcessLookupError, PermissionError):
        pass
    TOR_PID_FILE.unlink(missing_ok=True)


_BOOTSTRAP_TIMEOUT = 120  # seconds to wait for Tor to reach 100% bootstrap


def _port_in_use(port: int) -> bool:
    import socket
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        return s.connect_ex(("127.0.0.1", port)) == 0


def _kill_port(port: int) -> None:
    """Kill whatever process is holding a TCP port (macOS/Linux)."""
    try:
        result = subprocess.run(
            ["lsof", "-ti", f"tcp:{port}"],
            capture_output=True, text=True,
        )
        pids = result.stdout.strip().split()
        for pid in pids:
            try:
                os.kill(int(pid), signal.SIGTERM)
                logger.info(f"Killed stale process on port {port} (pid {pid})")
            except (ValueError, ProcessLookupError):
                pass
    except FileNotFoundError:
        pass  # lsof not available


def _wait_for_bootstrap(proc: subprocess.Popen, timeout: int = _BOOTSTRAP_TIMEOUT) -> None:
    """Read Tor's stdout until it reports Bootstrapped 100%, or raise on timeout/crash.

    Tor writes log messages to stdout by default. We merge stderr into stdout
    via subprocess so all output arrives on one stream.

    Tor opens its SOCKS port early during startup, well before it has built
    circuits. Waiting for the port to accept connections is not sufficient —
    actual proxy requests will time out until bootstrap is complete.
    """
    import threading

    lines: list[str] = []
    done = threading.Event()

    def _reader():
        try:
            for raw in proc.stdout:  # type: ignore[union-attr]
                line = raw.decode(errors="replace").rstrip()
                lines.append(line)
                pct = _parse_bootstrap_pct(line)
                if pct is not None:
                    logger.info(f"Tor bootstrap: {pct}%")
                if "Bootstrapped 100%" in line:
                    done.set()
                    return
        finally:
            # Always signal done when stdout closes (process exited or EOF),
            # so the main thread doesn't wait the full timeout on early exit.
            done.set()

    t = threading.Thread(target=_reader, daemon=True)
    t.start()

    if not done.wait(timeout=timeout):
        proc.terminate()
        tail = "\n".join(lines[-15:])
        detail = f"\nTor output:\n{tail}" if tail else " (no output captured)"
        raise RuntimeError(
            f"Tor did not finish bootstrapping within {timeout}s.{detail}"
        )

    # If the process has already exited it crashed — show why.
    rc = proc.poll()
    if rc is not None and rc != 0:
        tail = "\n".join(lines[-15:])
        raise RuntimeError(
            f"Tor exited before bootstrapping (rc={rc}):\n{tail}"
        )


def _parse_bootstrap_pct(line: str) -> Optional[int]:
    """Extract bootstrap percentage from a Tor log line, or return None."""
    import re
    m = re.search(r"Bootstrapped (\d+)%", line)
    return int(m.group(1)) if m else None


def ensure_tor(exit_countries: Optional[list[str]] = None) -> str:
    """Ensure Tor is running and fully bootstrapped with exit nodes pinned to friendly countries.

    Returns the SOCKS5 proxy URL (e.g. socks5h://127.0.0.1:9050).
    """
    tor_bin = shutil.which("tor")
    if not tor_bin:
        raise RuntimeError(
            "Tor is not installed. Install with: brew install tor"
        )

    torrc = _write_torrc(exit_countries)

    if _is_tor_running():
        # Reload config (SIGHUP) so new exit nodes take effect without restarting
        pid = int(TOR_PID_FILE.read_text().strip())
        os.kill(pid, signal.SIGHUP)
        logger.info(f"Reloaded Tor config (pid {pid})")
    else:
        # Kill anything already holding port 9050 (e.g. a stale brew-managed Tor)
        if _port_in_use(TOR_SOCKS_PORT):
            logger.info(f"Port {TOR_SOCKS_PORT} already in use — stopping existing Tor process...")
            _kill_port(TOR_SOCKS_PORT)
            # Brief pause for the OS to release the port
            import time
            time.sleep(2)

        logger.info("Starting Tor — waiting for full bootstrap (this may take ~60s)...")
        proc = subprocess.Popen(
            [tor_bin, "-f", str(torrc)],
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,  # merge stderr into stdout
        )

        try:
            _wait_for_bootstrap(proc)
        except RuntimeError:
            TOR_PID_FILE.unlink(missing_ok=True)
            raise

        TOR_PID_FILE.write_text(str(proc.pid))
        logger.info(f"Tor ready (pid {proc.pid}) — circuits built, proxy active on port {TOR_SOCKS_PORT}")

    proxy_url = f"socks5h://127.0.0.1:{TOR_SOCKS_PORT}"
    return proxy_url


def apply_proxy(proxy_url: str) -> None:
    """Route CLOB trading traffic (httpx) through the proxy while keeping
    Gamma market-discovery traffic (requests) direct for speed.

    Polymarket's geoblocking only applies to the CLOB API (clob.polymarket.com).
    The Gamma API (gamma-api.polymarket.com) is read-only and does not geoblock.
    Routing Gamma through Tor adds ~5-10s latency per page of market results,
    which makes scans painfully slow. So we only proxy httpx (py_clob_client).

    Args:
        proxy_url: e.g. "socks5h://127.0.0.1:9050" for Tor.
                   Use socks5h so DNS resolves on the proxy side.
    """
    global _patched
    if _patched:
        return
    if not proxy_url:
        return

    # ── 1. httpx monkey-patch (CLOB / trading) ────────────────
    # py_clob_client constructs httpx.Client() internally. Patching __init__
    # ensures every Client gets the proxy even if it was already imported.
    try:
        import httpx

        _original_client_init = httpx.Client.__init__

        def _patched_client_init(self, *args, **kwargs):
            kwargs.setdefault("proxy", proxy_url)
            _original_client_init(self, *args, **kwargs)

        httpx.Client.__init__ = _patched_client_init

        _original_async_client_init = httpx.AsyncClient.__init__

        def _patched_async_client_init(self, *args, **kwargs):
            kwargs.setdefault("proxy", proxy_url)
            _original_async_client_init(self, *args, **kwargs)

        httpx.AsyncClient.__init__ = _patched_async_client_init

        logger.info("httpx (CLOB) proxy patch applied — trading calls routed through proxy")
    except ImportError:
        pass  # httpx not installed — py_clob_client won't be usable anyway

    # NOTE: requests (Gamma API) is intentionally NOT proxied.
    # Gamma is read-only, not geoblocked, and proxying it through Tor
    # adds massive latency to market scans.

    _patched = True
    logger.info(f"Proxy active: {proxy_url} (CLOB only, Gamma direct)")


def check_proxy(proxy_url: str) -> bool:
    """Quick connectivity check — verifies the proxy is reachable and working.

    Uses httpx (the library that will actually be proxied) for the check.
    """
    try:
        import httpx
        with httpx.Client(proxy=proxy_url, timeout=15) as client:
            resp = client.get("https://httpbin.org/ip")
            ip = resp.json().get("origin", "unknown")
            logger.info(f"Proxy exit IP: {ip}")
            return True
    except Exception as e:
        logger.error(f"Proxy check failed: {e}")
        return False
